image:
  replicas: 1

curatorResources:
  resources:
    requests:
      cpu: 100m
      memory: 1.0Gi
    limits:
      cpu: 150m
      memory: 1.5Gi

registrySecretName: registry-key

downloadConcurrency: "10"
sleepFor: 15