image:
  replicas: 1

curatorResources:
  resources:
    requests:
      cpu: 100m
      memory: 1.0Gi
    limits:
      cpu: 150m
      memory: 1.5Gi

registrySecretName: registry-key

download-concurrency: "10"
sleep-for: 15