snapshot: lts-24.29

# pantry has Cabal <3.15 bound but we need 3.16 for casa-curator
allow-newer: true
allow-newer-deps:
  - pantry

extra-deps:
  # Needed for casa-curator, which pulls bleeding edge packages from Hackage.
  - Cabal-3.16.1.0
  - Cabal-syntax-3.16.1.0

nix:
  shell-file: shell-stack.nix

# For local dev
# - ../pantry
# - ../casa/casa-client
# - ../casa/casa-types
