# Generated by update-deps
{ mkDerivation, aeson, base, bytestring, Cabal, casa-client
, conduit, containers, hspec, http-client, http-client-tls
, http-conduit, http-download, http-types, lens, lib, monad-logger
, optparse-applicative, optparse-simple, pantry, path, path-io
, persistent, persistent-sqlite, process, resourcet, rio
, rio-orphans, rio-prettyprint, tar, text, time, unix, yaml
}:
mkDerivation {
  pname = "curator";
  version = "2.1.0.0";
  src = ../..;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson base bytestring Cabal conduit http-client http-client-tls
    http-conduit http-types pantry path path-io process rio
    rio-prettyprint tar unix yaml
  ];
  executableHaskellDepends = [
    aeson base bytestring casa-client conduit containers http-client
    http-client-tls http-conduit http-download lens monad-logger
    optparse-applicative optparse-simple pantry path path-io persistent
    persistent-sqlite resourcet rio rio-orphans text time yaml
  ];
  testHaskellDepends = [ base Cabal containers hspec rio text ];
  license = lib.licenses.bsd3;
}
