# Generated by ./nix/scripts/gen-packages.sh
{ mkDerivation, aeson, attoparsec-aeson, base, bytestring, Cabal
, casa-client, conduit, containers, hspec, http-client
, http-client-tls, http-conduit, http-download, lens, lib
, monad-logger, optparse-applicative, optparse-simple, pantry, path
, path-io, persistent, persistent-sqlite, persistent-template
, resourcet, rio, rio-orphans, rio-prettyprint, syb, tar, text
, time, yaml
}:
mkDerivation {
  pname = "curator";
  version = "2.0.0.0";
  src = ../../.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson base bytestring Cabal conduit http-client http-client-tls
    pantry path path-io rio rio-prettyprint tar yaml
  ];
  executableHaskellDepends = [
    aeson attoparsec-aeson base bytestring casa-client conduit
    containers http-client http-client-tls http-conduit http-download
    lens monad-logger optparse-applicative optparse-simple pantry path
    path-io persistent persistent-sqlite persistent-template resourcet
    rio rio-orphans rio-prettyprint syb text time yaml
  ];
  testHaskellDepends = [
    base Cabal containers hspec http-client http-client-tls pantry path
    path-io rio rio-prettyprint text yaml
  ];
  license = lib.licenses.bsd3;
}
