#!/usr/bin/env bash

set -Eeuo pipefail

filter=${1:-.}

gen () {
    f="$(mktemp)"
    # shellcheck disable=SC2064
    trap "rm -f $f" EXIT
    if grep -q "$filter" <<< "$1"; then
        echo "Generating $1..."
        echo "# Generated by $0" > "$f"
        cabal2nix "$2" >> "$f" "${@:3}"
        mv "$f" "${1}.nix"
    else
        echo "Skipping $1..."
    fi
}

cd "$(pwd)"

cd nix/packages

gen curator ../..

# Need the latest Cabal file format to support all packages on Hackage
gen Cabal cabal://Cabal-3.16.1.0
gen Cabal-syntax cabal://Cabal-syntax-3.16.1.0

echo "Success!"
