#!/usr/bin/env bash

set -Eeuo pipefail

# Retry a command with exponential backoff
retry() {
    local max_attempts=3
    local delay=2
    local attempt=1

    while (( attempt <= max_attempts )); do
        if "$@"; then
            return 0
        fi
        echo "Attempt $attempt/$max_attempts failed, retrying in ${delay}s..." >&2
        sleep "$delay"
        (( attempt++ ))
        (( delay *= 2 ))
    done

    echo "All $max_attempts attempts failed" >&2
    return 1
}

filter=${1:-.}

gen () {
    f="$(mktemp)"
    # shellcheck disable=SC2064
    trap "rm -f $f" EXIT
    if grep -q "$filter" <<< "$1"; then
        echo "Generating $1..."
        echo "# Generated by $0" > "$f"
        retry cabal2nix "$2" >> "$f" "${@:3}"
        mv "$f" "${1}.nix"
    else
        echo "Skipping $1..."
    fi
}

cd "$(pwd)"

cd nix/packages

gen curator ../..

# Need the latest Cabal file format to support all packages on Hackage
gen Cabal cabal://Cabal-3.16.1.0
gen Cabal-syntax cabal://Cabal-syntax-3.16.1.0

echo "Success!"
