#!/usr/bin/env bash
#
# Update all dependencies in one go.
#
# Usage: nix run .#update-deps
#
# This script:
# 1. Updates nixpkgs flake input
# 2. Syncs stack.yaml snapshot with nixpkgs LTS version
# 3. Checks Hackage for new Cabal versions
# 4. Regenerates nix package definitions

set -Eeuo pipefail

# Retry a command with exponential backoff
retry() {
    local max_attempts=3
    local delay=2
    local attempt=1

    while (( attempt <= max_attempts )); do
        if "$@"; then
            return 0
        fi
        echo "Attempt $attempt/$max_attempts failed, retrying in ${delay}s..." >&2
        sleep "$delay"
        (( attempt++ ))
        (( delay *= 2 ))
    done

    echo "All $max_attempts attempts failed" >&2
    return 1
}

# Temp files for parallel job results
lts_result=$(mktemp)
cabal_result=$(mktemp)
trap 'rm -f "$lts_result" "$cabal_result"' EXIT

#
# Step 1: Update flake inputs
#
echo "=== Updating flake inputs ==="
nix flake update

#
# Step 2: Fetch LTS and Cabal info in parallel
#
echo ""
echo "=== Fetching LTS and Cabal versions (parallel) ==="

# Background job: Get LTS version from GitHub
(
    nixpkgs_date=$(jq -r '.nodes.nixpkgs.locked.lastModified' flake.lock)
    nixpkgs_date_iso=$(date -d "@$nixpkgs_date" -u +%Y-%m-%dT%H:%M:%SZ)

    search_result=$(retry gh api "search/commits" \
        -X GET \
        -f q="repo:NixOS/nixpkgs haskellPackages stackage LTS committer-date:<=$nixpkgs_date_iso" \
        -f sort="committer-date" \
        -f order="desc" \
        -f per_page=1 \
        --jq '.items[0].commit.message')

    if [[ -z "$search_result" || "$search_result" == "null" ]]; then
        echo "Error: Could not find LTS commit" >&2
        exit 1
    fi

    lts_version=$(echo "$search_result" | grep -oP 'LTS \K[0-9]+\.[0-9]+' | tail -1)
    if [[ -z "$lts_version" ]]; then
        echo "Error: Could not parse LTS version" >&2
        exit 1
    fi

    echo "$lts_version"
) > "$lts_result" &
lts_pid=$!

# Background job: Get latest Cabal versions from Hackage
(
    cabal_ver=$(retry curl -sH "Accept: application/json" \
        "https://hackage.haskell.org/package/Cabal/preferred" | jq -r '.["normal-version"][0]')
    cabal_syntax_ver=$(retry curl -sH "Accept: application/json" \
        "https://hackage.haskell.org/package/Cabal-syntax/preferred" | jq -r '.["normal-version"][0]')
    echo "$cabal_ver $cabal_syntax_ver"
) > "$cabal_result" &
cabal_pid=$!

# Wait for both
wait "$lts_pid" || { echo "LTS fetch failed"; exit 1; }
wait "$cabal_pid" || { echo "Cabal fetch failed"; exit 1; }

lts_version=$(cat "$lts_result")
read -r cabal_latest cabal_syntax_latest < "$cabal_result"

echo "LTS version: $lts_version"
echo "Cabal: $cabal_latest, Cabal-syntax: $cabal_syntax_latest"

#
# Step 3: Update stack.yaml
#
echo ""
echo "=== Updating stack.yaml ==="

current_snapshot=$(grep -oP '^snapshot: lts-\K[0-9]+\.[0-9]+' stack.yaml || echo "")
if [[ "$current_snapshot" != "$lts_version" ]]; then
    echo "Updating snapshot: lts-$current_snapshot -> lts-$lts_version"
    sed -i "s/^snapshot: lts-.*/snapshot: lts-$lts_version/" stack.yaml
else
    echo "Snapshot already at lts-$lts_version"
fi

cabal_current=$(grep -oP "^  - Cabal-\\K[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+" stack.yaml || echo "")
if [[ "$cabal_current" != "$cabal_latest" ]]; then
    echo "Updating Cabal: $cabal_current -> $cabal_latest"
    sed -i "s/- Cabal-${cabal_current}/- Cabal-${cabal_latest}/" stack.yaml
else
    echo "Cabal already at $cabal_latest"
fi

cabal_syntax_current=$(grep -oP "^  - Cabal-syntax-\\K[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+" stack.yaml || echo "")
if [[ "$cabal_syntax_current" != "$cabal_syntax_latest" ]]; then
    echo "Updating Cabal-syntax: $cabal_syntax_current -> $cabal_syntax_latest"
    sed -i "s/- Cabal-syntax-${cabal_syntax_current}/- Cabal-syntax-${cabal_syntax_latest}/" stack.yaml
else
    echo "Cabal-syntax already at $cabal_syntax_latest"
fi

#
# Step 4: Regenerate nix packages (parallel)
#
echo ""
echo "=== Regenerating nix packages (parallel) ==="

cd nix/packages

# All three cabal2nix calls in parallel
(
    echo "# Generated by update-deps" > curator.nix.tmp
    retry cabal2nix ../.. >> curator.nix.tmp
    mv curator.nix.tmp curator.nix
    echo "  curator: done"
) &
curator_pid=$!

(
    echo "# Generated by update-deps" > Cabal.nix.tmp
    retry cabal2nix "cabal://Cabal-${cabal_latest}" >> Cabal.nix.tmp
    mv Cabal.nix.tmp Cabal.nix
    echo "  Cabal: done"
) &
cabal_nix_pid=$!

(
    echo "# Generated by update-deps" > Cabal-syntax.nix.tmp
    retry cabal2nix "cabal://Cabal-syntax-${cabal_syntax_latest}" >> Cabal-syntax.nix.tmp
    mv Cabal-syntax.nix.tmp Cabal-syntax.nix
    echo "  Cabal-syntax: done"
) &
cabal_syntax_nix_pid=$!

wait "$curator_pid" || { echo "curator cabal2nix failed"; exit 1; }
wait "$cabal_nix_pid" || { echo "Cabal cabal2nix failed"; exit 1; }
wait "$cabal_syntax_nix_pid" || { echo "Cabal-syntax cabal2nix failed"; exit 1; }

cd ../..

echo ""
echo "=== All done! ==="
