#!/usr/bin/env bash
#
# Update all dependencies in one go.
#
# Usage: nix run .#update-deps
#
# This script:
# 1. Updates nixpkgs flake input
# 2. Syncs stack.yaml snapshot with nixpkgs LTS version
# 3. Checks Hackage for new Cabal versions
# 4. Regenerates nix package definitions

set -Eeuo pipefail

# Retry a command with exponential backoff
retry() {
    local max_attempts=3
    local delay=2
    local attempt=1

    while (( attempt <= max_attempts )); do
        if "$@"; then
            return 0
        fi
        echo "Attempt $attempt/$max_attempts failed, retrying in ${delay}s..." >&2
        sleep "$delay"
        (( attempt++ ))
        (( delay *= 2 ))
    done

    echo "All $max_attempts attempts failed" >&2
    return 1
}

#
# Step 1: Update flake inputs
#
echo "=== Updating flake inputs ==="
nix flake update

#
# Step 2: Sync LTS version with nixpkgs
#
echo ""
echo "=== Syncing LTS version ==="

nixpkgs_rev=$(jq -r '.nodes.nixpkgs.locked.rev' flake.lock)
nixpkgs_date=$(jq -r '.nodes.nixpkgs.locked.lastModified' flake.lock)
nixpkgs_date_iso=$(date -d "@$nixpkgs_date" -u +%Y-%m-%dT%H:%M:%SZ)

echo "nixpkgs rev: $nixpkgs_rev"
echo "nixpkgs date: $nixpkgs_date_iso"

echo "Searching for LTS version in nixpkgs history..."

search_result=$(retry gh api "search/commits" \
    -X GET \
    -f q="repo:NixOS/nixpkgs haskellPackages stackage LTS committer-date:<=$nixpkgs_date_iso" \
    -f sort="committer-date" \
    -f order="desc" \
    -f per_page=1 \
    --jq '.items[0].commit.message')

if [[ -z "$search_result" || "$search_result" == "null" ]]; then
    echo "Error: Could not find LTS commit via search" >&2
    exit 1
fi

echo "Found commit: $search_result"

lts_version=$(echo "$search_result" | grep -oP 'LTS \K[0-9]+\.[0-9]+' | tail -1)

if [[ -z "$lts_version" ]]; then
    echo "Error: Could not parse LTS version from commit message" >&2
    exit 1
fi

echo "LTS version: $lts_version"

current_snapshot=$(grep -oP '^snapshot: lts-\K[0-9]+\.[0-9]+' stack.yaml || echo "")

if [[ "$current_snapshot" == "$lts_version" ]]; then
    echo "stack.yaml already uses lts-$lts_version"
else
    echo "Updating stack.yaml: lts-$current_snapshot -> lts-$lts_version"
    sed -i "s/^snapshot: lts-.*/snapshot: lts-$lts_version/" stack.yaml
fi

#
# Step 3: Check for new Cabal versions
#
echo ""
echo "=== Checking for new Cabal ==="

get_latest_version() {
    local pkg="$1"
    retry curl -sH "Accept: application/json" "https://hackage.haskell.org/package/$pkg/preferred" | jq -r '.["normal-version"][0]'
}

get_current_version() {
    local pkg="$1"
    grep -oP "^  - ${pkg}-\\K[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+" stack.yaml || echo ""
}

cabal_latest=$(get_latest_version "Cabal")
cabal_syntax_latest=$(get_latest_version "Cabal-syntax")

echo "Latest on Hackage: Cabal $cabal_latest, Cabal-syntax $cabal_syntax_latest"

cabal_current=$(get_current_version "Cabal")
cabal_syntax_current=$(get_current_version "Cabal-syntax")

echo "Current in stack.yaml: Cabal $cabal_current, Cabal-syntax $cabal_syntax_current"

if [[ "$cabal_current" != "$cabal_latest" ]]; then
    echo "Updating Cabal: $cabal_current -> $cabal_latest"
    sed -i "s/- Cabal-${cabal_current}/- Cabal-${cabal_latest}/" stack.yaml
else
    echo "Cabal already up to date"
fi

if [[ "$cabal_syntax_current" != "$cabal_syntax_latest" ]]; then
    echo "Updating Cabal-syntax: $cabal_syntax_current -> $cabal_syntax_latest"
    sed -i "s/- Cabal-syntax-${cabal_syntax_current}/- Cabal-syntax-${cabal_syntax_latest}/" stack.yaml
else
    echo "Cabal-syntax already up to date"
fi

#
# Step 4: Regenerate nix package definitions
#
echo ""
echo "=== Regenerating nix packages ==="

cd nix/packages

echo "Generating curator..."
echo "# Generated by update-deps" > curator.nix.tmp
retry cabal2nix ../.. >> curator.nix.tmp
mv curator.nix.tmp curator.nix

echo "Generating Cabal..."
echo "# Generated by update-deps" > Cabal.nix.tmp
retry cabal2nix "cabal://Cabal-${cabal_latest}" >> Cabal.nix.tmp
mv Cabal.nix.tmp Cabal.nix

echo "Generating Cabal-syntax..."
echo "# Generated by update-deps" > Cabal-syntax.nix.tmp
retry cabal2nix "cabal://Cabal-syntax-${cabal_syntax_latest}" >> Cabal-syntax.nix.tmp
mv Cabal-syntax.nix.tmp Cabal-syntax.nix

cd ../..

echo ""
echo "=== All done! ==="
