FROM ghcr.io/commercialhaskell/curator/base-build:6b7b6b87cbac3b16d3267aab628de965402044dc as build-app

RUN mkdir -p /artifacts/bin
COPY . /src
RUN stack install --stack-yaml /src/stack.yaml --local-bin-path /artifacts/bin

FROM ghcr.io/commercialhaskell/curator/base-run:6b7b6b87cbac3b16d3267aab628de965402044dc

RUN mkdir -p /app/db
COPY --from=build-app /artifacts/bin/casa-curator /usr/local/bin/casa-curator
COPY --from=build-app /artifacts/bin/curator /usr/local/bin/curator
