FROM fpco/pid1:20.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    wget -qO- https://get.haskellstack.org/ | sh -x && \
    apt-get install -y \
      ca-certificates \
      libgmp-dev \
      netbase
