name: Update Dependencies

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/update-deps.yml'
      - 'nix/scripts/update-deps.sh'

jobs:
  call:
    uses: haskellfoundation/hf-infrastructure/.github/workflows/update-deps.yml@main
    permissions:
      contents: write
      pull-requests: write
